name: dartterminal
description: A sample web application
dependencies:
  browser: any
  unittest: any
  archive: any
  polymer: ">=0.12.0 <0.13.0"
transformers:
- polymer:
    entry_points: web/testpolymer.html